### ISSUE TITLE
Copyright Update

### ISSUE THREAD

**Issue by jjscheel** [riscv/riscv-indirect-csr-access#5]
Minor update needed to document: the copyright dates should be set to 2023 as the availability via Freeze would make it a product of 2023, not 2022.

**Comment by jjscheel** [comment]
Hey, @bcstrongx, we should clean this up before Freeze.  So, please let me know when you've made this change.

Other than this, the Spec Policy signoff is done.

**Comment by bcstrongx** [comment]
fixed here: https://github.com/riscv/riscv-indirect-csr-access/releases/tag/v1.0.0-rc8

**Comment by jjscheel** [comment]
Thanks, @bcstrongx!!!
